import pyautogui as pg
import time

pg.PAUSE = 2
pg.FAILSAFE = True

pg.hotkey('command','space')
time.sleep(2)
pg.typewrite('chrome', interval = 0.2)
pg.hotkey('enter')
pos = pg.locateOnScreen(r'/Users/vish/Desktop/searchbar.png')
x,y = pg.center(pos)
pg.moveTo(x, y, duration = 2)
pg.click(x, y)
time.sleep(40)
pg.typewrite('http://180.211.119.163:8081/PUMIS/', interval = 0.1)
pg.hotkey('enter')
pos = pg.locateOnScreen(r'/Users/vish/Desktop/student.png')
x,y = pg.center(pos)
pg.moveTo(x, y, duration = 2)
pg.click(x, y)
time.sleep(20)
pg.typewrite('150303105087', interval = 0.5)
pg.hotkey('tab')
pg.typewrite('*****', interval = 0.5)
pg.hotkey('enter')
time.sleep(20)
pos = pg.locateOnScreen(r'/Users/vish/Desktop/academic.png')
x,y = pg.center(pos)
pg.moveTo(x, y, duration = 2)
pos = pg.locateOnScreen(r'/Users/vish/Desktop/attend.png')
x,y = pg.center(pos)
pg.moveTo(x, y, duration = 2)
pg.click(x, y)
time.sleep(20)
pos = pg.locateOnScreen(r'/Users/vish/Desktop/hi.png')
x,y = pg.center(pos)
pg.moveTo(x, y, duration = 2)
pos = pg.locateOnScreen(r'/Users/vish/Desktop/logout.png')
x,y = pg.center(pos)
pg.moveTo(x, y, duration = 2)
pg.click(x, y)
